name: Build and Push Nginx Image to GHCR

on:
  push:
    branches: [ "main", "master" ]  # choose your default branch
  workflow_dispatch:                # manual trigger

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: nginx-proxy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ${{ env.REGISTRY }} -u "${{ github.repository_owner }}" --password-stdin

      - name: Build Nginx Docker image
        run: docker build -f Dockerfile -t ${{ env.IMAGE_NAME }}:latest .


      - name: Push Nginx image to GHCR
        run: |
          docker push ${{ env.IMAGE_NAME }}:latest

      # Optional: Trigger Portainer webhook for redeploy
    
